### ISSUE TITLE
跑脚本  奖励变为百分之一问题 怎么解决

### ISSUE THREAD

**Issue by DistantDream** [zhzhch335/taobao2020autojs#1]

**Comment by zhzhch335** [comment]
我目前也没招，今天才发现这个问题我自己的号也是被限制了
不太清楚淘宝那边的判断机制
晚上回去试试考虑用模拟点节点的坐标而不是直接点击节点看看吧
这事比较难办的是没法测试……手里就一个淘宝账号

**Comment by zhzhch335** [comment]
卸载当前手机淘宝，重新安装9.15及以下版本可以避免审核机制
https://www.apkmirror.com/apk/taobao/%e6%b7%98%e5%ae%9d-2/%e6%b7%98%e5%ae%9d-2-9-5-17-release/%e6%89%8b%e6%9c%ba%e6%b7%98%e5%ae%9d-9-5-17-android-apk-download/
